services:
  codevideo-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: codevideo-api
    container_name: codevideo-api
    ports:
      - "7000:7000"
    restart: always
    networks:
      - codevideo-network
    volumes:
      - ./tmp/v3/:/usr/src/app/tmp/v3/

  # major challenges with sound here, for now we will run non-dockerized on host machine(s)
  # go-video-dispatcher:
  #   build:
  #     context: ./go-video-dispatcher
  #     dockerfile: Dockerfile
  #   image: go-video-dispatcher
  #   container_name: go-video-dispatcher
  #   restart: always
  #   networks:
  #     - codevideo-network
  #   volumes:
  #     - ./tmp/v3/:/usr/src/app/tmp/v3/

  gatsby-static-server:
    build:
      context: ./gatsby-static-server
      dockerfile: Dockerfile
    image: gatsby-static-server
    container_name: gatsby-static-server
    ports:
      - "7001:7001"
    restart: always
    networks:
      - codevideo-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - codevideo-network
    depends_on:
      - codevideo-api
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/live/:/etc/nginx/ssl/live:ro
      - ./certbot/conf/archive/:/etc/nginx/ssl/archive:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  codevideo-network:
    driver: bridge