version: '3.8'

services:
  codevideo-backend-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: codevideo-backend-engine
    container_name: codevideo-backend-engine
    ports:
      - "7000:7000"
    restart: always
    networks:
      - codevideo-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - codevideo-network
    depends_on:
      - codevideo-backend-engine

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  codevideo-network:
    driver: bridge